var dir_5096da1bcae106b466f16b5bb1d74fa1 =
[
    [ "battery.c", "battery_8c.html", "battery_8c" ],
    [ "battery.h", "battery_8h.html", "battery_8h" ],
    [ "data_interface.c", "data__interface_8c.html", "data__interface_8c" ],
    [ "data_interface.h", "data__interface_8h.html", "data__interface_8h" ],
    [ "driver_callbacks.c", "driver__callbacks_8c.html", "driver__callbacks_8c" ],
    [ "driver_callbacks.h", "driver__callbacks_8h.html", "driver__callbacks_8h" ],
    [ "frame_check.c", "frame__check_8c.html", "frame__check_8c" ],
    [ "frame_check.h", "frame__check_8h.html", "frame__check_8h" ],
    [ "front_motor.c", "front__motor_8c.html", "front__motor_8c" ],
    [ "front_motor.h", "front__motor_8h.html", "front__motor_8h" ],
    [ "hall_sensors.c", "hall__sensors_8c.html", "hall__sensors_8c" ],
    [ "hall_sensors.h", "hall__sensors_8h.html", "hall__sensors_8h" ],
    [ "init.c", "init_8c.html", null ],
    [ "init.h", "init_8h.html", "init_8h" ],
    [ "mirroring.c", "mirroring_8c.html", "mirroring_8c" ],
    [ "mirroring.h", "mirroring_8h.html", "mirroring_8h" ],
    [ "modules_definitions.h", "modules__definitions_8h.html", "modules__definitions_8h" ],
    [ "motors.c", "motors_8c.html", "motors_8c" ],
    [ "motors.h", "motors_8h.html", "motors_8h" ],
    [ "position_sensors.c", "position__sensors_8c.html", "position__sensors_8c" ],
    [ "position_sensors.h", "position__sensors_8h.html", "position__sensors_8h" ],
    [ "rear_motors.c", "rear__motors_8c.html", "rear__motors_8c" ],
    [ "rear_motors.h", "rear__motors_8h.html", "rear__motors_8h" ],
    [ "speed_sensors.c", "speed__sensors_8c.html", "speed__sensors_8c" ],
    [ "speed_sensors.h", "speed__sensors_8h.html", "speed__sensors_8h" ],
    [ "spi_comm.c", "spi__comm_8c.html", "spi__comm_8c" ],
    [ "spi_comm.h", "spi__comm_8h.html", "spi__comm_8h" ],
    [ "system_time.c", "system__time_8c.html", "system__time_8c" ],
    [ "system_time.h", "system__time_8h.html", "system__time_8h" ],
    [ "us_sensors.c", "us__sensors_8c.html", null ],
    [ "us_sensors.h", "us__sensors_8h.html", null ]
];